version: '3.3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: cargo run
    links:
        - db
    ports:
    - "8000:8000"
    volumes:
    - ./server:/usr/src/app
    - ./server/registry:/root/.cargo/registry
    env_file: server/.env
    networks:
        - test
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: "db"
    environment:
      MYSQL_DATABASE: client
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret


networks:
  test:
      driver: bridge

#Todo :
#Configure Node in docker
#Configure DB for Rust app (for clients and all)
#Condifure networks properly
